remote_theme: broccolini/swiss
title: not just a portfolio
description: Welcome to a collection of works expressed in different mediums and seen through different lenses. In hopes, it connects the complexity and beauty of the world of architecture &design and my representations of it. 
theme_colour: black
github_username: zmmurzyn
github_maintainer: drew2a
linkedin_username: zuzanna-murzyn
